from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from app.models.repurposing import RepurposingCandidate
from app.models.graph import SubgraphResponse


class ChatMessage(BaseModel):
    role: str = Field(..., description="user, assistant, system, or tool")
    content: str
    name: Optional[str] = None
    tool_call_id: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None


class ToolExecutionRecord(BaseModel):
    tool_name: str
    arguments: Dict[str, Any]
    result_summary: str
    provenance_source: Optional[str] = None


class ChatRequest(BaseModel):
    message: str
    conversation_id: Optional[str] = None
    history: List[ChatMessage] = Field(default_factory=list)
    temperature: Optional[float] = 0.1
    include_subgraph: bool = True


class ChatResponse(BaseModel):
    conversation_id: str
    reply: str
    tool_executions: List[ToolExecutionRecord] = Field(default_factory=list)
    candidates: List[RepurposingCandidate] = Field(default_factory=list)
    subgraph: Optional[SubgraphResponse] = None
    medical_disclaimer: str = (
        "Drug repurposing hypotheses generated by this system are computational research findings "
        "and are not medical advice or evidence of clinical efficacy."
    )
