from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from app.models.entities import Drug, Disease, Protein, Provenance


class EvidenceClassification(str, Enum):
    ESTABLISHED = "Established evidence"
    STRONG_COMPUTATIONAL = "Strong computational evidence"
    MODERATE_COMPUTATIONAL = "Moderate computational evidence"
    WEAK_EVIDENCE = "Weak evidence"
    HYPOTHESIS = "Hypothesis"


class ScoreBreakdown(BaseModel):
    """Granular explainable score components with mathematical derivation."""
    target_association: float = Field(..., ge=0.0, le=1.0, description="Score based on direct target affinity (pChEMBL/IC50) and Open Targets association")
    pathway_overlap: float = Field(..., ge=0.0, le=1.0, description="Jaccard similarity and pathway intersection between drug targets and disease pathways")
    network_proximity: float = Field(..., ge=0.0, le=1.0, description="Graph network proximity / Personalized PageRank score in the biomedical network")
    clinical_evidence: float = Field(..., ge=0.0, le=1.0, description="Clinical trial validation status (Phase 1-4) for related conditions or targets")
    publication_evidence: float = Field(..., ge=0.0, le=1.0, description="Co-occurrence and validated scientific citations in PubMed/EuropePMC")
    genetic_score: float = Field(default=0.0, ge=0.0, le=1.0, description="Genetic evidence score (GWAS, ClinVar, L2G) from Open Targets")
    calculation_details: Dict[str, str] = Field(default_factory=dict, description="Human-readable formula breakdown for each score component")


class BiologicalPathStep(BaseModel):
    node_type: str = Field(..., description="Disease, Gene, Protein, Pathway, Target, or Drug")
    node_id: str
    node_name: str
    relation_to_next: Optional[str] = None
    provenance: Optional[Provenance] = None


class BiologicalPath(BaseModel):
    strategy: str = Field(..., description="Direct Target Overlap, Pathway Co-occurrence, PPI Network Proximity, Indication Pivot")
    description: str
    steps: List[BiologicalPathStep] = Field(default_factory=list)


class EvidenceItem(BaseModel):
    category: str = Field(..., description="Target, Genetic, Pathway, Clinical Trial, or Literature")
    title: str
    detail: str
    confidence: float = 1.0
    source: str
    source_id: str
    source_url: Optional[str] = None


class RepurposingCandidate(BaseModel):
    drug: Drug
    overall_score: float = Field(..., ge=0.0, le=1.0, description="Combined computational evidence score")
    score_breakdown: ScoreBreakdown
    classification: EvidenceClassification
    mechanism_hypothesis: str
    biological_paths: List[BiologicalPath] = Field(default_factory=list)
    key_targets: List[Dict[str, Any]] = Field(default_factory=list)
    key_pathways: List[str] = Field(default_factory=list)
    evidence_items: List[EvidenceItem] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    safety_disclaimer: str = (
        "Drug repurposing hypotheses generated by this system are computational research findings "
        "and are not medical advice or evidence of clinical efficacy."
    )


class RepurposingRequest(BaseModel):
    disease_id_or_name: str = Field(..., description="Disease name or canonical ID (e.g. Alzheimer's disease or EFO_0000249)")
    max_candidates: int = Field(default=10, ge=1, le=50)
    min_score: float = Field(default=0.3, ge=0.0, le=1.0)
    approved_only: bool = Field(default=False, description="Restrict to FDA/EMA approved drugs")
    strategies: Optional[List[str]] = Field(
        default=["direct_target", "pathway_overlap", "ppi_network", "indication_pivot"],
        description="Graph traversal strategies to execute"
    )


class RepurposingResponse(BaseModel):
    disease: Disease
    total_candidates_found: int
    candidates: List[RepurposingCandidate]
    execution_time_seconds: float
    graph_stats: Dict[str, Any] = Field(default_factory=dict)
    medical_disclaimer: str = (
        "Drug repurposing hypotheses generated by this system are computational research findings "
        "and are not medical advice or evidence of clinical efficacy."
    )
