'use client';

import React, { useState } from 'react';
import { ShieldAlert, X } from 'lucide-react';

export default function MedicalDisclaimer() {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  return (
    <div className="w-full bg-surface-raised/80 border-b border-surface-border px-4 py-1.5 text-[11px] text-gray-400 flex items-center justify-between">
      <div className="mx-auto flex items-center space-x-2">
        <span className="inline-flex items-center space-x-1 rounded bg-amber-500/10 border border-amber-500/20 px-1.5 py-0.2 text-[10px] font-mono text-amber-400 font-medium">
          <ShieldAlert className="h-3 w-3 inline" />
          <span>RESEARCH SYSTEM</span>
        </span>
        <span className="hidden sm:inline">
          Drug repurposing candidates generated by DrugCopilot are computational hypotheses for research investigation only.
        </span>
        <span className="sm:hidden">
          Computational hypotheses for research only.
        </span>
      </div>
      <button
        onClick={() => setDismissed(true)}
        className="p-1 text-gray-500 hover:text-gray-300 rounded transition-colors"
        title="Dismiss notice"
      >
        <X className="h-3 w-3" />
      </button>
    </div>
  );
}
