'use client';

import { AlertTriangle } from 'lucide-react';

export default function MedicalDisclaimer() {
  return (
    <div className="w-full bg-amber-950/40 border-b border-amber-500/20 px-4 py-2.5 text-xs text-amber-200/90 flex items-center justify-center space-x-2">
      <AlertTriangle className="h-4 w-4 text-amber-400 shrink-0" />
      <span>
        <strong>Research Disclaimer:</strong> Drug repurposing hypotheses generated by this system are computational research findings and are not medical advice or evidence of clinical efficacy.
      </span>
    </div>
  );
}
