import logging
import asyncio
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import settings
from app.graph.schema import init_schema
from app.graph.driver import Neo4jConnectionManager
from app.ingestion.bootstrap import bootstrap_biomedical_graph
from app.api.routes_drugs import router as drugs_router
from app.api.routes_diseases import router as diseases_router
from app.api.routes_targets import router as targets_router
from app.api.routes_trials import router as trials_router
from app.api.routes_repurposing import router as repurposing_router
from app.api.routes_copilot import router as copilot_router
from app.api.routes_graph import router as graph_router
from app.api.routes_ingestion import router as ingestion_router
from app.api.routes_evidence import router as evidence_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("app.main")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting up %s (version %s)...", settings.PROJECT_NAME, settings.VERSION)
    # Initialize schema
    try:
        await init_schema()
    except Exception as e:
        logger.warning("Schema initialization notice: %s", e)

    # Initial seed bootstrap in background so the API is immediately responsive with real data
    asyncio.create_task(bootstrap_biomedical_graph())

    yield

    logger.info("Shutting down %s...", settings.PROJECT_NAME)
    await Neo4jConnectionManager.close()


app = FastAPI(
    title=settings.PROJECT_NAME,
    version=settings.VERSION,
    description="AI Drug Repurposing Copilot powered by a Neo4j Biomedical Knowledge Graph with real-world data from ChEMBL, Open Targets, UniProt, PubChem, ClinicalTrials.gov, and PubMed.",
    lifespan=lifespan
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(drugs_router)
app.include_router(diseases_router)
app.include_router(targets_router)
app.include_router(trials_router)
app.include_router(repurposing_router)
app.include_router(copilot_router)
app.include_router(graph_router)
app.include_router(ingestion_router)
app.include_router(evidence_router)


@app.get("/health", tags=["Health"])
async def health_check():
    """Health check endpoint for container orchestrators and monitoring."""
    neo4j_connected = await Neo4jConnectionManager.is_connected()
    return {
        "status": "healthy",
        "service": settings.PROJECT_NAME,
        "version": settings.VERSION,
        "environment": settings.ENVIRONMENT,
        "database": {
            "type": "Neo4j / In-Memory Graph Hybrid",
            "neo4j_live_connected": neo4j_connected,
            "status": "active"
        },
        "disclaimer": "Drug repurposing hypotheses generated by this system are computational research findings and are not medical advice or evidence of clinical efficacy."
    }


@app.get("/", tags=["Root"])
async def root():
    return {
        "message": "Drug Repurposing Copilot API is running",
        "docs": "/docs",
        "health": "/health"
    }
